# Generated by Django 6.1.1 on 2026-09-13 16:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependents', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('education', models.CharField(choices=[('Graduate', 'Graduate'), ('High School', 'High School'), ('Postgrad', 'Postgrad')], max_length=20)),
                ('employment_status', models.CharField(choices=[('Employed', 'Employed'), ('Self-Employed', 'Self-Employed'), ('Unemployed', 'Unemployed')], max_length=20)),
                ('occupation_type', models.CharField(choices=[('Business', 'Business'), ('Freelancer', 'Freelancer'), ('Professional', 'Professional'), ('Salaried', 'Salaried')], max_length=20)),
                ('residential_status', models.CharField(choices=[('Own', 'Own'), ('Rent', 'Rent'), ('Other', 'Other')], max_length=20)),
                ('city_town', models.CharField(choices=[('Urban', 'Urban'), ('Suburban', 'Suburban'), ('Rural', 'Rural')], max_length=20)),
                ('annual_income', models.FloatField(validators=[django.core.validators.MinValueValidator(20009), django.core.validators.MaxValueValidator(149998)])),
                ('monthly_expenses', models.FloatField(validators=[django.core.validators.MinValueValidator(500), django.core.validators.MaxValueValidator(4999)])),
                ('credit_score', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(849)])),
                ('existing_loans', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)])),
                ('total_existing_loan_amount', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(49999)])),
                ('outstanding_debt', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(29998)])),
                ('loan_history', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('loan_amount_requested', models.FloatField(validators=[django.core.validators.MinValueValidator(5000), django.core.validators.MaxValueValidator(44848)])),
                ('loan_term', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(12), django.core.validators.MaxValueValidator(239)])),
                ('loan_purpose', models.CharField(choices=[('Education', 'Education'), ('Home', 'Home'), ('Personal', 'Personal'), ('Vehicle', 'Vehicle')], max_length=20)),
                ('loan_type', models.CharField(choices=[('Secured', 'Secured'), ('Unsecured', 'Unsecured')], max_length=20)),
                ('co_applicant', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('bank_account_history', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)])),
                ('transaction_frequency', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(29)])),
                ('model_recommendation', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('approval_probability', models.FloatField(blank=True, null=True)),
                ('risk_score', models.FloatField(blank=True, null=True)),
                ('secondary_recommendation', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('secondary_probability', models.FloatField(blank=True, null=True)),
                ('system_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Under Review', 'Under Review')], default='Pending', max_length=20)),
                ('review_reason', models.CharField(blank=True, max_length=200)),
                ('human_decision', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
